SoftwareTechnologiesTeamProject/Models/Post.cs
namespace SoftwareTechnologiesTeamProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Globalization;
    using System.Linq;
    using System.Web.Mvc;
    using ViewModels;

    public class Post
    {
        public Post()
        {
            this.Date = DateTime.Now;
            this.LastDateActive = DateTime.Now;
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [AllowHtml]
        [StringLength(200)]
        public string Title { get; set; }

        [Required]
        [AllowHtml]
        public string Body { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Column(TypeName = "datetime2")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyy}",
               ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        public DateTime LastDateActive { get; set; }

        public virtual List<ApplicationUser> VotedUsers { get; set; } = new List<ApplicationUser>();

        public string AuthorId { get; set; }

        [Display(Name = "Author")]
        [ForeignKey("AuthorId")]
        public ApplicationUser Author { get; set; }

        [NotMapped]
        public Image Image { get; set; }

        public virtual List<Comment> Comments { get; set; }

        public virtual List<Tag> Tags { get; set; } = new List<Tag>();

        public string ShortBody()
        {
            if (this.Body.Length > 300)
            {
                return this.Body.Substring(0, 300);
            }
            else
            {
                return this.Body;
            }
        }

        public string FullBody()
        {
            if (this.Body.Length > 300)
            {
                return this.Body.Substring(300);
            }

            return string.Empty;
        }

        public void AddTags(string[] tagNames, List<Tag> existingTags)
        {
            foreach (var tagName in tagNames)
            {
                if (existingTags.FirstOrDefault(t => t.Name == tagName) == null)
                {
                    Tags.Add(new Tag
                    {
                        Name = tagName,
                        Posts = new List<Post>() { this }
                    });
                }
                else
                {
                    Tag tag = existingTags.First(t => t.Name == tagName);
                    this.Tags.Add(tag);
                    tag.Posts.Add(this);
                }
            }
        }

        public string GetTagNames()
        {
            string tagNames = "";

            if (Tags.Count != 0)
            {
                tagNames = "#" + string.Join("#", Tags.Select(t => t.Name));
            }

            return tagNames;
        }

        public void Update(ApplicationUser author, EditPostViewModel viewModel)
        {
            this.Author = author;
            this.AuthorId = author.Id;
            this.Title = viewModel.Title;
            this.Date = DateTime.Now;
            this.Body = viewModel.Body;
        }

        public bool HasUserVoted(string userId)
        {
            return this.VotedUsers.Select(u => u.Id).ToList().Contains(userId);
        }

        public string GetDate()
        {
            string date = this.Date.ToString("dd.MMMM.yyyy", CultureInfo.InvariantCulture);
            return date;
        }

        public string GetTime()
        {
            return $"{Date:H:mm}";
        }

        public string GetShortTitle()
        {
            if (this.Title.Length > 40)
            {
                return this.Title.Substring(0, 40) + "...";
            }

            return this.Title;
        }

        public Comment GetRecentComment()
        {
            return this.Comments.OrderByDescending(c => c.DateCreated).First();
        }

        public void SetImage(List<Image> images)
        {

            this.Image = images.Where(i => i.ImagePath.Contains("PostId_" + this.Id))
                    .OrderByDescending(i => i.UploadedDate)
                    .FirstOrDefault();
        }
    }
}

SoftwareTechnologiesTeamProject/Controllers/ImagesController.cs
using SoftwareTechnologiesTeamProject.Extensions;
using SoftwareTechnologiesTeamProject.Models;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SoftwareTechnologiesTeamProject.Controllers
{
    public class ImagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private readonly string[] allowedFileExtensions = new[] { "png", "jpg", "jpeg", "gif" };

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddHomePageImage(HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file == null)
                {
                    this.AddNotification("Choose image!", NotificationType.ERROR);
                    return RedirectToAction("Index", "Home");
                }

                var fileExtension = file.FileName.Split('.').Last();
                if (!allowedFileExtensions.Contains(fileExtension.ToLower()))
                {
                    this.AddNotification("Not allowed file extension", NotificationType.ERROR);
                    return RedirectToAction("Index", "Home");
                }

                Image img = new Image();

                string homePageImgName = "homepage" + file.FileName;


                file.SaveAs(HttpContext.Server.MapPath("~/Content/Images/HomePage/")
                                                            + homePageImgName);
                img.ImagePath = homePageImgName;

                img.UploadedDate = DateTime.Now;

                db.Images.Add(img);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");

            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPostImage(HttpPostedFileBase file)
        {

            if (ModelState.IsValid)
            {
                string check = HttpContext.Request.FilePath.Split('/').Last();
                int postId = int.Parse(check);
                Image img = new Image();

                if (file == null)
                {
                    this.AddNotification("Choose image!", NotificationType.ERROR);
                    return RedirectToAction("Details", "Posts", new { id = postId });
                }

                var fileExtension = file.FileName.Split('.').Last();
                if (!allowedFileExtensions.Contains(fileExtension.ToLower()))
                {
                    this.AddNotification("Not allowed file extension", NotificationType.ERROR);
                    return RedirectToAction("Details", "Posts", new { id = postId });
                }

                string postImgName = "PostId_" + check + file.FileName;

                file.SaveAs(HttpContext.Server.MapPath("~/Content/Images/PostImages/")
                                                            + postImgName);
                img.ImagePath = postImgName;

                img.UploadedDate = DateTime.Now;

                db.Images.Add(img);
                db.SaveChanges();

                return RedirectToAction("Details", "Posts", new { id = postId });


            }
            return View("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SoftwareTechnologiesTeamProject/Controllers/PostsController.cs
namespace SoftwareTechnologiesTeamProject.Controllers
{
    using Extensions;
    using Microsoft.AspNet.Identity;
    using Models;
    using System;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using ViewModels;

    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Posts 
        public ActionResult Index(string searchString)
        {
            var posts = db.Posts
                .Include(p => p.Author)
                .OrderByDescending(p => p.Date)
                .ToList();

            var images = db.Images.ToList();

            //Setting each post iamge
            foreach (var post in posts)
            {
                post.SetImage(images);
            }

            //Getting popular tags
            var popularTags = db.Tags
                .OrderByDescending(t => t.Posts.Count)
                .Take(10)
                .ToList();

            var viewModel = new PostIndexViewModel
            {
                PopularTags = popularTags
            };


            if (!string.IsNullOrEmpty(searchString))
            {
                var searchedPosts = posts
                    .Where(p => p.Title.Contains(searchString) || p.Author.FullName.Contains(searchString) || p.Body.Contains(searchString))
                    .ToList();

                viewModel.Posts = searchedPosts;

                return View(viewModel);
            }

            viewModel.Posts = posts;

            return View(viewModel);
        }

        public ActionResult Tag(int? id)
        {
            var tags = db.Tags.Include(t => t.Posts.Select(p => p.Author)).ToList();

            var tag = tags.FirstOrDefault(t => t.Id == id);

            if (tag == null)
            {
                return HttpNotFound();
            }

            var posts = tag.Posts.ToList();
            var images = db.Images.ToList();
            foreach (var post in posts)
            {
                post.SetImage(images);
            }
            ViewBag.Header = tag.Name;

            TagsIndexViewModel viewModel = new TagsIndexViewModel

            {
                Posts = posts,
                PopularTags = tags.OrderByDescending(t => t.Posts.Count).Take(5).ToList()
            };


            return View(viewModel);
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Post post = db.Posts
                .Include(p => p.Author)
                .Include(p => p.Comments.Select(c => c.Author))
                .Include(p => p.Tags)
                .First(p => p.Id == id);



            if (post == null)
            {
                this.AddNotification("Error occurred while trying to load post deitals.", NotificationType.ERROR);
                return RedirectToAction("Index", "Posts");
            }

            var postImage = db.Images
              .OrderByDescending(i => i.UploadedDate)
              .FirstOrDefault(i => i.ImagePath.Contains("PostId_" + post.Id));


            var viewModel = new PostDetailsViewModel
            {
                Post = post,
                CommentAuthorId = User.Identity.GetUserId(),
                PostId = post.Id,
                PostImage = postImage
            };


            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment([Bind(Include = "NewCommentContent,PostId,CommentAuthorId")] PostDetailsViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var author = db.Users.Find(viewModel.CommentAuthorId);
                Comment newComment = new Comment
                {
                    PostId = viewModel.PostId,
                    Author = author,
                    Content = viewModel.NewCommentContent,
                    AuthorId = viewModel.CommentAuthorId
                };

                author.Comments.Add(newComment);
                db.Comments.Add(newComment);
                db.SaveChanges();

                return RedirectToAction("Details", new { id = viewModel.PostId });
            }

            viewModel.Post = db.Posts
                .Include(p => p.Author)
                .Include(p => p.Comments.Select(c => c.Author))
                .First(p => p.Id == viewModel.PostId);

            this.AddNotification("Error while adding the comment.", NotificationType.ERROR);
            return View("Details", viewModel);
        }

        public ActionResult DeleteComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Comment comment = db.Comments.Find(id);

            int postId = comment.PostId;
            db.Comments.Remove(comment);
            db.SaveChanges();

            return RedirectToAction("Details", new { id = postId });
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditComment(Comment comment)
        {
            comment.Author = db.Users.FirstOrDefault(u => u.Id == comment.AuthorId);
            comment.DateCreated = DateTime.Now;

            db.Entry(comment).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Details", new { id = comment.PostId });
        }

        // GET: Posts/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Body,AuthorId,Tags")] CreatePostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Post post = new Post
                {
                    Author = db.Users.FirstOrDefault(u => u.Id == viewModel.AuthorId),
                    Title = viewModel.Title,
                    Body = viewModel.Body,
                    AuthorId = viewModel.AuthorId,
                };

                var existingTags = db.Tags.ToList();
                var inputTags = viewModel.GetTags();
                if (inputTags[0] != string.Empty)
                {
                    post.AddTags(inputTags, existingTags);
                }

                db.Posts.Add(post);
                db.SaveChanges();

                this.AddNotification("Post created successfully.", NotificationType.SUCCESS);
                return RedirectToAction("Details", new { id = post.Id });
            }

            this.AddNotification("Error while creating the post.", NotificationType.ERROR);
            return View();
        }

        // GET: Edit
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Post post = db.Posts.Include(p => p.Author).FirstOrDefault(p => p.Id == id);

            if (post == null)
            {
                this.AddNotification("Sorry this post does not exist.", NotificationType.ERROR);
                return HttpNotFound();
            }

            if (User.Identity.GetUserId() != post.AuthorId && !User.IsInRole("Administrator"))
            {
                this.AddNotification("You are not admin nor the post owner.", NotificationType.INFO);
                return RedirectToAction("Index");
            }

            EditPostViewModel viewModel = new EditPostViewModel(post, post.GetTagNames());

            return View(viewModel);
        }

        //POST Edit
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditPostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Post post = db.Posts.Include(p => p.Author).First(p => p.Id == viewModel.PostId);
                post.Tags.Clear();

                if (post.Author == null)
                    return HttpNotFound();

                var author = db.Users.FirstOrDefault(u => u.UserName == viewModel.AuthorUserName);
                if (author == null)
                {
                    this.AddNotification("Username does not exist.", NotificationType.ERROR);
                    return RedirectToAction("Edit", post.Id);
                }

                post.Update(author, viewModel);

                string[] tagNames = viewModel.GetTagNames();
                var allExistingTags = db.Tags.ToList();
                post.AddTags(tagNames, allExistingTags);

                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();

                this.AddNotification("Post edited successfully.", NotificationType.SUCCESS);
                return RedirectToAction("Details", new { post.Id });
            }

            this.AddNotification("Could not edit the post. The input data is not valid.", NotificationType.ERROR);
            return View(viewModel);
        }

        // GET: Posts/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }

            if (User.Identity.GetUserId() != post.AuthorId && !User.IsInRole("Administrator"))
            {
                return RedirectToAction("Index");
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]

SoftwareTechnologiesTeamProject/Views/Posts/Create.cshtml
@using Microsoft.AspNet.Identity
@model SoftwareTechnologiesTeamProject.ViewModels.CreatePostViewModel

@Styles.Render("~/Content/css")

@{
    ViewBag.Title = "Create post";
}

<h2>Create new post</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Post</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control text-box"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, 30, 70, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Body, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tags, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Tags, new {@class = "form-control text-box", placeholder = "#example1#example2#example3"})
                @Html.ValidationMessageFor(model => model.Tags, "", new {@class = "text-danger"})
            </div>
        </div>

        @Html.Hidden("AuthorId", User.Identity.GetUserId())
        <div class="col-md-1"></div>
        <div class="col-md-1">
            <div class="postButtons">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8"></div>
    </div>
}


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

SoftwareTechnologiesTeamProject/Views/Posts/Delete.cshtml
@model SoftwareTechnologiesTeamProject.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <button class="button" style="vertical-align: middle"><span>@Html.ActionLink("Back to List", "Index")</span></button>
        </div>
    }
</div>

SoftwareTechnologiesTeamProject/Views/Posts/Details.cshtml
@using Microsoft.AspNet.Identity
@model SoftwareTechnologiesTeamProject.ViewModels.PostDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<div class="post-info-wrapper">
    
    <hr/>

    <div class="col-md-8">
        <h2>@Html.DisplayFor(model => model.Post.Title)</h2>

        <p><span class="glyphicon glyphicon-time"></span> Posted on @Html.DisplayFor(model => model.Post.LastDateActive)</p>
        <h3>By <span>@Html.DisplayFor(model => model.Post.Author.FullName)</span>
        </h3>
    </div>

    <div>
        
        <div class="col-md-8">
            
            @if (Model.PostImage != null)
            {
                
                    <img class="img-responsive" src="~/Content/Images/PostImages/@Model.PostImage.ImagePath" alt="Bar" />
                
                if (User.IsInRole("Administrator") || (Model.Post.Author != null && User.Identity.Name == Model.Post.Author.UserName))
                {
                    using (Html.BeginForm("AddPostImage/" + Html.DisplayFor(model => model.Post.Id), "Images", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <fieldset>
                            <div class="editor-label">
                                @Html.Label("Change image")
                            </div>
                            <div class="editor-field">
                                <input id="ImagePath" title="Upload a product image"
                                       type="file" name="file"/>
                            </div>
                            <p>
                                <input type="submit" value="Change"/>
                            </p>
                        </fieldset>
                    }
                }
            }
            else
            {
                if (User.IsInRole("Administrator") || (Model.Post.Author != null && User.Identity.Name == Model.Post.Author.UserName))
                {

                    <img class="img-responsive" src="~/Content/Images/AddImage.jpg" alt="">

                    using (Html.BeginForm("AddPostImage/" + Html.DisplayFor(model => model.Post.Id), "Images", null, FormMethod.Post, new {enctype = "multipart/form-data"}))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <fieldset>
                            <div class="editor-label">
                                @Html.Label("Change image")
                            </div>
                            <div class="editor-field">
                                <input id="ImagePath" title="Upload a product image"
                                       type="file" name="file"/>
                            </div>
                            <p>
                                <input type="submit" value="Add Image"/>
                            </p>
                        </fieldset>
                    }
                }
            }

            <hr/>
        </div>
        <div class="post-details-content">
                <div class="row">
                    <div class="col-md-8"> @Html.DisplayFor(model => model.Post.Body)</div>
                </div>
        </div>
    </div>
    <div class="tag-container">
        Tags:
        @foreach (var tag in Model.Post.Tags)
        {
            @Html.ActionLink(tag.Name, "Tag", new {id = tag.Id, @class = "tagLink"})
        }
    </div>
    <div class="likesContainer">
        @if (Model.Post.HasUserVoted(User.Identity.GetUserId()))
        {
            <span class="glyphicon glyphicon-heart liked paddingLeft"></span>
        }
        else
        {

            @Html.ActionLink(" ", "AddLike", new { id = Model.Post.Id }, new { @class = "glyphicon glyphicon-heart paddingLeft" })
        }
        <span class="likesCount">@Model.Post.VotedUsers.Count</span>
    </div>
    <p>
        @if (User.IsInRole("Administrator") || (Model.Post.Author != null && User.Identity.Name == Model.Post.Author.UserName))
        {
            <button class="button paddingLeft" style="vertical-align: middle"><span>@Html.ActionLink("Edit", "Edit", new {id = Model.PostId})</span></button>
            <button class="button paddingLeft" style="vertical-align: middle"><span>@Html.ActionLink("Delete", "Delete", new { id = Model.PostId })</span></button>
            <br/>
        }
        <button class="button paddingLeft" style="vertical-align: middle"><span>@Html.ActionLink("Back to List", "Index")</span></button>
        
    </p>
</div>
<div class="add-comment-wrapper paddingLeft">
    @using (Html.BeginForm("AddComment", "Posts", FormMethod.Post))
    {
        @Html.ValidationMessageFor(model => model.NewCommentContent, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(m => m.PostId)
        @Html.HiddenFor(m => m.CommentAuthorId)

        @Html.TextAreaFor(m => m.NewCommentContent, new { @class = "add-comment-text-area" })
        <input type="submit" value="Add comment" class="bottom-right" />
    }

</div>



<div class="comments-wrapper paddingLeft">
    <br />
    <h1>Comments(@Model.Post.Comments.Count)</h1>
    <hr />
    <div class="comments">
        @foreach (var comment in Model.Post.Comments)
        {
            <div class="single-comment" id="single-comment-@comment.Id">
                <div class="info">
                    <p>
                        <strong>@comment.Author.FullName</strong> - <i>@comment.DateCreated</i>
                    </p>
                </div>

                <div class="actions">
                    @if (User.IsInRole("Administrators") || User.Identity.Name == comment.Author.UserName)
                    {
                        <br/>
                        <a id="deleteLink-@comment.Id" class="confirmDeleteLink" onclick="showConfirmDelete(@comment.Id)">Delete</a>
                        <a onclick="showEditPostDiv(@comment.Id)" id="editLink-@comment.Id" class="cancelConfirmDelete">Edit</a>
                    }
                </div>

                <div class="single-comment-content" id="@comment.Id-content">
                    @Html.DisplayFor(m => comment.Content)
                </div>
                @using (Html.BeginForm("EditComment", "Posts", FormMethod.Post, new {@class = " hidden edit-form", id = comment.Id}))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new {@class = "text-danger"})

                    @Html.HiddenFor(m => comment.AuthorId)
                    @Html.HiddenFor(m => comment.Id)
                    @Html.HiddenFor(c => comment.DateCreated)
                    @Html.HiddenFor(c => comment.PostId)

                    @Html.TextAreaFor(m => comment.Content)
                    @Html.ValidationMessageFor(model => model.NewCommentContent, "", new {@class = "text-danger"})

                    <div class="edit-comment-actions">
                        <input type="submit" value="Edit" class="edit-comment-button btn btn-primary"/>
                        <a onclick="cancelEdit(@comment.Id)" class="edit-comment-cancel-link">Cancel</a>
                    </div>
                }

            </div>
            <hr />
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function showEditPostDiv(commentId) {
            $("#" + commentId).removeClass("hidden");
            $('#' + commentId + "-content").hide();
            $("#editLink-" + commentId).hide();
            $("#deleteLink-" + commentId).hide();
        }

        function cancelEdit(commentId) {
            $("#" + commentId).addClass("hidden");
            $('#' + commentId + "-content").show();
            $("#editLink-" + commentId).show();
            $("#deleteLink-" + commentId).show();
        }

        function showConfirmDelete(commentId) {
            $("#single-comment-" + commentId).children().hide();
            let confirmDeleteElements =
                "<div id='confirmDelete-"+ commentId + "' class='confirmDelete'>" +
                    "<p>Confirm delete</p>" +
                    "<a href='/Posts/DeleteComment/" + commentId + "' class='confirmDeleteLink'>Delete</a>" +
                    "<a id='cancelDelete-"+ commentId + "' onclick='cancelConfirmDelete(" + commentId + ")' class='cancelConfirmDelete'>Cancel</a>" +
                    "</div>";
            $("#single-comment-" + commentId)
                .append(confirmDeleteElements);
        }

        function cancelConfirmDelete(commentId) {
            $("#confirmDelete-" + commentId).remove();
            $("#single-comment-" + commentId).children().show();
        }

    </script>
}